### PR TITLE
Remove trailing whitespace from README.

### PR DESCRIPTION
**Pull request by vanniktech**
No need for the trailing whitespace.

### CODE REVIEW

**Comment by vanniktech** [comment]
Best reviewed like this: https://github.com/uber/crumb/pull/30/files?w=1

**Comment by vanniktech** [comment]
I'm pretty sure I've signed the CLA already. On artist I'm already a contributor - https://github.com/uber/artist/commits?author=vanniktech

**Comment by tyvsmith** [comment]
@vanniktech CLA-Assistant requires you to resign when the CLA has been changed. In this case we fixed a couple typos. Sorry for the inconvenience!

**Comment by vanniktech** [comment]
Alright cool, signed it again.

**Pull request merged**
